apiVersion: v1
kind: Service
metadata:
  name: otakuracy-api
  namespace: apps
spec:
  type: NodePort
  selector:
    app: otakuracy-api
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30900
